### ISSUE TITLE
how about the plan for supporting on linux ?

### ISSUE THREAD

**Issue by saleemshenlin** [DHI/mikepluspy#81]

**Comment by ryan-kipawa** [comment]
Hi @saleemshenlin 

Since this package requires MIKE+, it can only provide the same Linux support that MIKE+ does. Linux support will be automatic when MIKE+ provides it fully, since there's nothing in MIKE+Py that's tied to Windows (aside from MIKE+).

FYI, this is the status from MIKE+ 2025 release:
![image](https://github.com/user-attachments/assets/f72f55da-1a07-4009-9e23-7b68ebff11ca)

**Comment by saleemshenlin** [comment]
thx, a lot
